In [12]:
import os

os.environ["DOLT_HOST"] = "localhost"
import pandas as pd
import stats
import importlib

In [ ]:
importlib.reload(stats)

import yfinance as yf
import fred
import numpy as np
from curl_cffi import requests

session = requests.Session(impersonate="chrome")

predict = pd.read_csv("rs3000.csv").iloc[:, 1:]
benchmark_close = (
    yf.Ticker("SPY", session=session)
    .history(period="5y", interval="1mo")
    .Close.reset_index(drop=True)
)
rf_rate = np.float64(fred.rf_rate())
stats.value_score("MSFT", predict.loc[:, "MSFT"], benchmark_close, rf_rate)

INFO:stats:Scoring MSFT

{'ticker': 'MSFT',
 'sector': 'Technology',
 'wacc': 0.1347953574349856,
 'est_price': 24.84112084842514,
 'price': 505.82000732421875,
 'diff': -480.9788864757936,
 'score': -0.950889406332829}

In [3]:
scores_df = pd.read_csv("scores1.csv").iloc[:, 1:]
scores_df["quantile"] = pd.qcut(scores_df["score"], 5, labels=False)
scores_df.sort_values(["quantile", "score"], ascending=False)

,ticker,sector,wacc,est_price,price,diff,score,quantile
221,BIIB,Healthcare,0.036578,2640.795490,143.660004,2497.135486,17.382260,4
149,GIS,Consumer Defensive,0.045227,283.465224,62.330002,221.135222,3.547814,4
212,SYF,Financial Services,0.139648,217.542602,51.990002,165.552601,3.184316,4
106,MET,Financial Services,0.115998,251.388757,78.449997,172.938760,2.204446,4
223,DECK,Consumer Cyclical,0.155369,359.897824,120.529999,239.367825,1.985961,4
...,...,...,...,...,...,...,...,...
209,FE,Utilities,0.064817,-92.187576,39.150002,-131.337578,-3.354727,0
127,XEL,Utilities,0.062733,-185.024073,68.730003,-253.754077,-3.692042,0
226,ES,Utilities,0.067766,-225.701023,60.540001,-286.241024,-4.728130,0
111,D,Utilities,0.076647,-210.004014,55.139999,-265.144013,-4.808560,0
99,GM,Consumer Cyclical,0.070707,-193.519974,48.279999,-241.799973,-5.008285,0

In [7]:
scores_df[scores_df["ticker"] == "MSFT"]

,ticker,sector,wacc,est_price,price,diff,score,quantile
1,MSFT,Technology,0.134474,111.449798,380.450012,-269.000214,-0.707058,2

In [4]:
scores_df["score"].describe()

count    248.000000
mean      -0.567571
std        1.514368
min       -5.008285
25%       -0.828613
50%       -0.683494
75%       -0.413730
max       17.382260
Name: score, dtype: float64

In [5]:
sector_groups = pd.read_csv("scores1.csv").iloc[:, 1:].groupby("sector")
for name, group in sector_groups:
    group["quantile"] = pd.qcut(group["score"], min(5, len(group)), labels=False)
    print(group["score"].describe())
    print(group.sort_values(["quantile", "score"], ascending=False))

count    12.000000
mean     -0.874753
std       0.424624
min      -1.644924
25%      -0.956842
50%      -0.806928
75%      -0.742523
max      -0.161241
Name: score, dtype: float64
    ticker           sector      wacc   est_price       price        diff  \
234    LYB  Basic Materials  0.117712   62.034641   73.959999  -11.925358
164    NUE  Basic Materials  0.169915   76.058160  129.899994  -53.841834
119   CTVA  Basic Materials  0.122574   23.817760   59.970001  -36.152241
96     FCX  Basic Materials  0.203657    7.567632   35.880001  -28.312369
163    VMC  Basic Materials  0.111310   44.753995  224.710007 -179.956012
20     LIN  Basic Materials  0.132915   89.053701  454.070007 -365.016306
242   STLD  Basic Materials  0.162648   22.946963  120.760002  -97.813039
173    MLM  Basic Materials  0.121628   79.647843  464.410004 -384.762161
188    PPG  Basic Materials  0.146984   17.123259  113.430000  -96.306742
225    IFF  Basic Materials  0.126454  -22.385810   79.879997 -102.265807
189    DOW  Basic Materials  0.116007  -18.774635   36.669998  -55.444633
81     APD  Basic Materials  0.111739 -192.238793  298.079987 -490.318779

        score  quantile
234 -0.161241         4
164 -0.414487         4
119 -0.602839         4
96  -0.789085         3
163 -0.800837         3
20  -0.803877         2
242 -0.809979         2
173 -0.828497         1
188 -0.849041         1
225 -1.280243         0
189 -1.511989         0
81  -1.644924         0
count    7.000000
mean    -0.738282
std      0.268483
min     -1.168276
25%     -0.842679
50%     -0.775266
75%     -0.619370
max     -0.300336
Name: score, dtype: float64
    ticker                  sector      wacc  est_price       price  \
143     EA  Communication Services  0.117163  96.469745  137.880005
3    GOOGL  Communication Services  0.147023  62.807695  164.039993
5     GOOG  Communication Services  0.147032  62.803560  165.979996
215    LYV  Communication Services  0.162718  27.336687  121.639999
24     DIS  Communication Services  0.158149  19.967746   97.900002
11    NFLX  Communication Services  0.178777  99.070435  895.099976
135   TTWO  Communication Services  0.116652 -34.294558  203.800003

           diff     score  quantile
143  -41.410260 -0.300336         4
3   -101.232298 -0.617120         4
5   -103.176435 -0.621620         3
215  -94.303313 -0.775266         2
24   -77.932256 -0.796039         1
11  -796.029541 -0.889319         0
135 -238.094561 -1.168276         0
count    23.000000
mean     -0.722989
std       1.106698
min      -5.008285
25%      -0.769800
50%      -0.628799
75%      -0.492296
max       1.985961
Name: score, dtype: float64
    ticker             sector      wacc    est_price        price  \
223   DECK  Consumer Cyclical  0.155369   359.897824   120.529999
198    WSM  Consumer Cyclical  0.227974   145.912238   174.919998
174    LEN  Consumer Cyclical  0.203709    81.661466   121.440002
217    NVR  Consumer Cyclical  0.165368  4695.563156  7361.220215
197   EXPE  Consumer Cyclical  0.191920    97.620473   163.750000
211    PHM  Consumer Cyclical  0.203802    62.290980   105.839996
131    DHI  Consumer Cyclical  0.200046    56.572932   132.529999
110   ROST  Consumer Cyclical  0.150469    52.890225   128.649994
182     IP  Consumer Cyclical  0.117001    19.033216    49.380001
12      HD  Consumer Cyclical  0.142068   139.195145   368.160004
122   LULU  Consumer Cyclical  0.166688   119.708820   319.420013
32    BKNG  Consumer Cyclical  0.175281  1615.989058  4353.410156
35     TJX  Consumer Cyclical  0.137399    38.249129   116.120003
93     AZO  Consumer Cyclical  0.105894  1157.972958  3562.760010
36     LOW  Consumer Cyclical  0.130701    62.792568   232.669998
201    DRI  Consumer Cyclical  0.167739    49.508580   189.389999
171   TSCO  Consumer Cyclical  0.122872    12.802285    53.919998
68    ORLY  Consumer Cyclical  0.129171   295.224956  1324.060059
75     CMG  Consumer Cyclical  0.173215     9.059074    49.980000
92     HLT  Consumer Cyclical  0.154229    20.001728   231.830002
91     MAR  Consumer Cyclical  0.178821     5.453269   246.309998
200   CVNA  Consumer Cyclical  0.367926   -37.693595   172.220001
99      GM  Consumer Cyclical  0.070707  -193.519974    48.279999

            diff     score  quantile
223   239.367825  1.985961         4
198   -29.007760 -0.165834         4
174   -39.778536 -0.327557         4
217 -2665.657059 -0.362122         4
197   -66.129527 -0.403844         4
211   -43.549016 -0.411461         3
131   -75.957067 -0.573131         3
110   -75.759769 -0.588883         3
182   -30.346785 -0.614556         3
12   -228.964859 -0.621917         2
122  -199.711193 -0.625231         2
32  -2737.421098 -0.628799         2
35    -77.870874 -0.670607         2
93  -2404.787052 -0.674979         2
36   -169.877431 -0.730122         1
201  -139.881419 -0.738589         1
171   -41.117713 -0.762569         1
68  -1028.835102 -0.777031         1
75    -40.920926 -0.818746         0
92   -211.828274 -0.913722         0
91   -240.856728 -0.977860         0
200  -209.913596 -1.218869         0
99   -241.799973 -5.008285         0
count    15.000000
mean     -0.092693
std       1.084330
min      -0.802514
25%      -0.609574
50%      -0.456785
75%       0.017989
max       3.547814
Name: score, dtype: float64
    ticker              sector      wacc   est_price       price        diff  \
149    GIS  Consumer Defensive  0.045227  283.465224   62.330002  221.135222
183    KHC  Consumer Defensive  0.067075   49.265015   31.100000   18.165014
193    HSY  Consumer Defensive  0.072600  219.079899  179.539993   39.539905
56      MO  Consumer Defensive  0.090654   68.232024   58.150002   10.082023
74      CL  Consumer Defensive  0.078838   81.170535   94.099998  -12.929463
18      PM  Consumer Defensive  0.088580   98.599158  152.100006  -53.500848
59    MDLZ  Consumer Defensive  0.082643   41.059565   67.849998  -26.790433
98     TGT  Consumer Defensive  0.133326   61.252924  112.760002  -51.507079
22     PEP  Consumer Defensive  0.085611   79.362304  152.330002  -72.967698
247    CLX  Consumer Defensive  0.081402   63.755151  148.429993  -84.674841
125   MNST  Consumer Defensive  0.115803   21.900330   55.230000  -33.329670
133    KDP  Consumer Defensive  0.095369   12.774908   33.240002  -20.465094
138    SYY  Consumer Defensive  0.129809   21.221178   74.519997  -53.298819
15      KO  Consumer Defensive  0.093339   15.007049   71.040001  -56.032952
8     COST  Consumer Defensive  0.123975  183.758494  930.489990 -746.731496

        score  quantile
149  3.547814         4
183  0.584084         4
193  0.220229         4
56   0.173380         3
74  -0.137401         3
18  -0.351748         3
59  -0.394848         2
98  -0.456785         2
22  -0.479011         2
247 -0.570470         1
125 -0.603470         1
133 -0.615677         1
138 -0.715228         0
15  -0.788752         0
8   -0.802514         0
count    13.000000
mean     -0.548320
std       0.867598
min      -2.305875
25%      -0.882920
50%      -0.531632
75%      -0.368649
max       1.551740
Name: score, dtype: float64
    ticker  sector      wacc   est_price       price        diff     score  \
237   CTRA  Energy  0.065711   68.590762   26.879999   41.710763  1.551740
129    VLO  Energy  0.179945  131.131229  123.029999    8.101230  0.065848
7      XOM  Energy  0.117725   79.045668  109.160004  -30.114335 -0.275873
82     EOG  Energy  0.164867   78.596901  124.489998  -45.893097 -0.368649
104    PSX  Energy  0.141658   74.178280  123.550003  -49.371723 -0.399609
17     CVX  Energy  0.142909   87.380093  154.080002  -66.699909 -0.432891
166    OXY  Energy  0.140861   21.676077   46.279999  -24.603922 -0.531632
216    HAL  Energy  0.184974   10.745907   24.660000  -13.914093 -0.564237
108    LNG  Energy  0.105776   80.604700  211.369995 -130.765295 -0.618656
128    HES  Energy  0.148463   16.930933  144.610001 -127.679067 -0.882920
83     WMB  Energy  0.123958    1.746509   54.950001  -53.203491 -0.968216
218    DVN  Energy  0.176851  -13.667026   34.410000  -48.077026 -1.397182
186   FANG  Energy  0.187363 -188.894839  144.649994 -333.544833 -2.305875

     quantile
237         4
129         4
7           4
82          3
104         3
17          2
166         2
216         2
108         1
128         1
83          0
218         0
186         0
count    42.000000
mean      0.128138
std       1.069414
min      -1.451548
25%      -0.728164
50%      -0.365871
75%       0.843281
max       3.184316
Name: score, dtype: float64
    ticker              sector      wacc    est_price        price  \
212    SYF  Financial Services  0.139648   217.542602    51.990002
106    MET  Financial Services  0.115998   251.388757    78.449997
126    PRU  Financial Services  0.113663   308.280170   105.580002
155   ACGL  Financial Services  0.099183   244.977578    90.089996
232    PFG  Financial Services  0.134124   225.133301    82.879997
79     COF  Financial Services  0.137789   394.639505   165.399994
80     USB  Financial Services  0.109648    97.927976    41.560001
89      BK  Financial Services  0.178003   180.204692    81.050003
227   IBKR  Financial Services  0.144356   352.067502   170.339996
168    MTB  Financial Services  0.098554   349.915649   171.169998
30     PGR  Financial Services  0.077136   512.837804   276.940002
14     BAC  Financial Services  0.152441    71.999916    39.610001
46      CB  Financial Services  0.105019   502.358361   290.700012
207  FCNCA  Financial Services  0.066020  2705.797096  1728.359985
219   NTRS  Financial Services  0.194292   148.591429    97.489998
112    DFS  Financial Services  0.149063   230.817755   157.770004
180   FITB  Financial Services  0.122817    54.617978    38.230000
238    CFG  Financial Services  0.123999    45.892955    39.910000
210   HBAN  Financial Services  0.108634    13.253629    14.400000
228     RF  Financial Services  0.160521    18.266621    20.990000
41    SCHW  Financial Services  0.118844    46.169069    72.470001
25      GS  Financial Services  0.076277   335.427709   531.429993
33     AXP  Financial Services  0.139666   142.535382   255.389999
208   CBOE  Financial Services  0.106079   116.618888   211.160004
151    WTW  Financial Services  0.107703   163.450522   326.519989
213   TROW  Financial Services  0.194425    40.750914    96.300003
62     AJG  Financial Services  0.107254   135.571155   325.750000
45     MMC  Financial Services  0.123410    78.981992   233.110001
167   ARES  Financial Services  0.174854    47.315102   143.009995
177    BRO  Financial Services  0.122134    38.693173   117.959999
6        V  Financial Services  0.136302   100.203661   332.140015
158   NDAQ  Financial Services  0.118811    18.931588    72.290001
9       MA  Financial Services  0.151250   120.637353   525.799988
52     ICE  Financial Services  0.137516    37.566578   168.360001
31    SPGI  Financial Services  0.155378    98.312905   480.000000
64     KKR  Financial Services  0.163570    21.306440   112.110001
67     AON  Financial Services  0.121794    75.087819   399.739990
114   MSCI  Financial Services  0.151624    98.248646   541.719971
72     MCO  Financial Services  0.167753    75.987617   443.850006
49      BX  Financial Services  0.182898    18.277063   138.139999
195   LPLA  Financial Services  0.110482   -33.584493   313.230011
185    STT  Financial Services  0.140258   -38.706686    85.720001

           diff     score  quantile
212  165.552601  3.184316         4
106  172.938760  2.204446         4
126  202.700168  1.919873         4
155  154.887582  1.719254         4
232  142.253303  1.716377         4
79   229.239511  1.385970         4
80    56.367975  1.356303         4
89    99.154689  1.223377         4
227  181.727506  1.066852         4
168  178.745650  1.044258         3
30   235.897801  0.851801         3
14    32.389915  0.817721         3
46   211.658349  0.728099         3
207  977.437111  0.565529         3
219   51.101431  0.524171         3
112   73.047751  0.463002         3
180   16.387978  0.428668         3
238    5.982955  0.149911         2
210   -1.146371 -0.079609         2
228   -2.723379 -0.129746         2
41   -26.300932 -0.362922         2
25  -196.002283 -0.368821         2
33  -112.854617 -0.441891         2
208  -94.541116 -0.447723         2
151 -163.069467 -0.499416         2
213  -55.549089 -0.576834         1
62  -190.178845 -0.583818         1
45  -154.128009 -0.661181         1
167  -95.694893 -0.669148         1
177  -79.266826 -0.671981         1
6   -231.936353 -0.698309         1
158  -53.358413 -0.738116         1
9   -405.162635 -0.770564         1
52  -130.793422 -0.776868         0
31  -381.687095 -0.795181         0
64   -90.803560 -0.809951         0
67  -324.652172 -0.812158         0
114 -443.471325 -0.818636         0
72  -367.862390 -0.828799         0
49  -119.862936 -0.867692         0
195 -346.814504 -1.107220         0
185 -124.426687 -1.451548         0
count    23.000000
mean      0.277301
std       3.760461
min      -1.458364
25%      -0.739891
50%      -0.621508
75%      -0.213125
max      17.382260
Name: score, dtype: float64
    ticker      sector      wacc    est_price        price         diff  \
221   BIIB  Healthcare  0.036578  2640.795490   143.660004  2497.135486
165    HUM  Healthcare  0.087426   445.860754   250.199997   195.660758
76    REGN  Healthcare  0.069435   975.939854   718.159973   257.779881
63     CVS  Healthcare  0.072628    81.887381    64.980003    16.907378
88     BDX  Healthcare  0.069316   216.686726   224.919998    -8.233273
121    COR  Healthcare  0.090290   248.339389   260.670013   -12.330624
10     UNH  Healthcare  0.100679   301.856789   486.040009  -184.183220
13    ABBV  Healthcare  0.093854   127.769400   213.589996   -85.820596
156    RMD  Healthcare  0.117103    99.578158   225.789993  -126.211836
42     MDT  Healthcare  0.110515    38.603918    93.279999   -54.676081
214     LH  Healthcare  0.136760    94.147048   239.250000  -145.102952
37     DHR  Healthcare  0.118956    77.821740   205.610001  -127.788260
19     ABT  Healthcare  0.109703    48.605657   132.660004   -84.054347
157   VEEV  Healthcare  0.133445    79.974310   231.679993  -151.705683
139      A  Healthcare  0.144866    38.889149   121.029999   -82.140849
224    ZBH  Healthcare  0.128521    34.285010   107.339996   -73.054986
70     ZTS  Healthcare  0.132367    47.187434   164.389999  -117.202566
190    MTD  Healthcare  0.152347   289.872918  1243.170044  -953.297126
142   IDXX  Healthcare  0.182979    68.636357   426.690002  -358.053646
115     EW  Healthcare  0.155920     9.230470    68.389999   -59.159530
205    STE  Healthcare  0.124930    29.879194   228.059998  -198.180803
159   ALNY  Healthcare  0.083172    -2.082029   238.740005  -240.822035
169    CNC  Healthcare  0.063322   -26.846352    58.570000   -85.416351

         score  quantile
221  17.382260         4
165   0.782017         4
76    0.358945         4
63    0.260194         4
88   -0.036605         4
121  -0.047304         3
10   -0.378947         3
13   -0.401801         3
156  -0.558979         3
42   -0.586150         2
214  -0.606491         2
37   -0.621508         2
19   -0.633607         2
157  -0.654807         2
139  -0.678682         1
224  -0.680594         1
70   -0.712954         1
190  -0.766828         1
142  -0.839142         0
115  -0.865032         0
205  -0.868985         0
159  -1.008721         0
169  -1.458364         0
count    28.000000
mean     -0.679920
std       0.401495
min      -2.272705
25%      -0.819123
50%      -0.712364
75%      -0.503676
max       0.002855
Name: score, dtype: float64
    ticker       sector      wacc   est_price        price         diff  \
194    GPN  Industrials  0.104599   93.516264    93.250000     0.266264
87     NOC  Industrials  0.067230  460.545478   494.109985   -33.564507
170    UAL  Industrials  0.121922   60.700671    76.059998   -15.359327
61     UPS  Industrials  0.121262   80.828334   116.360001   -35.531666
77      GD  Industrials  0.096839  167.398322   264.119995   -96.721673
100   PCAR  Industrials  0.123297   59.695556   104.720001   -45.024445
78    CTAS  Industrials  0.173223  106.923563   196.559998   -89.636434
137    DAL  Industrials  0.136538   22.426967    46.680000   -24.253034
124    LHX  Industrials  0.103726   98.074319   212.330002  -114.255682
86     EMR  Industrials  0.164691   43.795559   110.720001   -66.924442
240   HUBB  Industrials  0.131787  131.369348   340.420013  -209.050665
29     CAT  Industrials  0.143956  125.560589   339.769989  -214.209400
117    AME  Industrials  0.157040   56.091630   178.860001  -122.768371
245    LII  Industrials  0.154802  170.496281   566.169983  -395.673702
71     ITW  Industrials  0.150832   69.854598   254.820007  -184.965409
148   ODFL  Industrials  0.155826   43.328086   167.029999  -123.701913
118    GWW  Industrials  0.156926  253.912130   981.539978  -727.627848
136    PWR  Industrials  0.143809   63.049742   246.029999  -182.980257
109   CPRT  Industrials  0.176274   11.429611    52.910000   -41.480389
116   FAST  Industrials  0.149059   16.033683    77.349998   -61.316315
120   VRSK  Industrials  0.128475   53.459231   290.529999  -237.070768
147     IR  Industrials  0.174311   14.214950    82.889999   -68.675049
44      DE  Industrials  0.126207   77.233912   475.500000  -398.266088
65      PH  Industrials  0.184139   94.814769   611.190002  -516.375233
66     MMM  Industrials  0.128977   20.538351   147.539993  -127.001642
130   AXON  Industrials  0.157817   54.134895   526.640015  -472.505120
73     TDG  Industrials  0.148944  -46.785308  1319.869995 -1366.655303
47      BA  Industrials  0.149665 -196.072875   154.059998  -350.132873

        score  quantile
194  0.002855         4
87  -0.067929         4
170 -0.201937         4
61  -0.305360         4
77  -0.366204         4
100 -0.429951         4
78  -0.456026         3
137 -0.519559         3
124 -0.538104         3
86  -0.604448         3
240 -0.614096         3
29  -0.630454         2
117 -0.686394         2
245 -0.698860         2
71  -0.725867         2
148 -0.740597         2
118 -0.741312         2
136 -0.743731         1
109 -0.783980         1
116 -0.792713         1
120 -0.815994         1
147 -0.828508         1
44  -0.837573         0
65  -0.844869         0
66  -0.860795         0
130 -0.897207         0
73  -1.035447         0
47  -2.272705         0
count    19.000000
mean     -0.808734
std       0.334995
min      -1.766132
25%      -0.931651
50%      -0.796243
75%      -0.654231
max      -0.261808
Name: score, dtype: float64
    ticker       sector      wacc   est_price       price        diff  \
103      O  Real Estate  0.096114   41.862876   56.709999  -14.847123
105    PSA  Real Estate  0.103349  206.674835  308.209991 -101.535157
101    DLR  Real Estate  0.086316   77.189643  147.009995  -69.820352
152   VICI  Real Estate  0.108195   13.599876   32.349998  -18.750122
154    EXR  Real Estate  0.110037   58.931397  151.850006  -92.918609
161    AVB  Real Estate  0.115983   64.616153  212.940002 -148.323849
233    ESS  Real Estate  0.110057   89.053138  295.540009 -206.486870
199   SBAC  Real Estate  0.089429   62.997963  220.419998 -157.422035
235    MAA  Real Estate  0.112759   42.783843  165.000000 -122.216157
48     PLD  Real Estate  0.126943   23.876231  117.180000  -93.303769
222   INVH  Real Estate  0.127449    6.856431   33.880001  -27.023570
53     AMT  Real Estate  0.104396   39.596606  209.779999 -170.183393
123    CCI  Real Estate  0.099723    9.263172   97.629997  -88.366825
160   CSGP  Real Estate  0.134019    5.707549   76.870003  -71.162454
206     WY  Real Estate  0.164865    1.847242   29.580000  -27.732758
94     SPG  Real Estate  0.161193   -0.544086  163.479996 -164.024082
60    EQIX  Real Estate  0.105239  -65.640450  836.239990 -901.880440
172    VTR  Real Estate  0.137131  -15.783346   66.699997  -82.483343